### ISSUE TITLE
nq-nci

### ISSUE THREAD

**Issue by TTTT555** [theimpulson/android_device_xiaomi_begonia#1]
https://github.com/HyperTeam/android_device_redmi_begonia/blob/eca8d5dd9f45a76ec88548ebbfadd9c8b30932c1/device.mk#L64

**Comment by TTTT555** [comment]
https://github.com/LineageOS/android_device_xiaomi_perseus/blob/34afc3833da636805f9fe5bd0edd93c744028c24/device.mk#L73

**Comment by TTTT555** [comment]
but vendor files is have in vendor

**Comment by TTTT555** [comment]
https://github.com/LineageOS/android_device_xiaomi_perseus/blob/34afc3833da636805f9fe5bd0edd93c744028c24/BoardConfig.mk#L38

**Comment by theimpulson** [comment]
I will try to fix it, will post updates here when I do so.

**Comment by TTTT555** [comment]
Try first in BoardConfig.mk flag

**Comment by theimpulson** [comment]
@TTTT555 I have a build ready, in case you wish to test, here is the link: https://drive.google.com/open?id=1fsuI48kZ_QvfpVr9WK2m3qdiYoTjpKT_

**Comment by theimpulson** [comment]
I have removed the build as I got it tested. It didn't work but there is progress. I will try with prebuilt apks and hidls tomorrow and update here if I make any progress.

**Comment by TTTT555** [comment]
fixed
