### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by ochorocho** [theimpulson/android_device_xiaomi_begonia#3]
Hey,

just  installed lineageOS (lineage-17.1-20200606-UNOFFICIAL-begonia.zip, twrp-3.4.0-0-begonia.img recovery) and GAPPS (open_gapps-FIXED-arm64-10.0-nano-20200131.zip)

Works great so far. But audio is not working at all. Tested alarm, phone call and youtube.

Log when trying to play a video on Youtube: 
[log.txt](https://github.com/HyperTeam/android_device_redmi_begonia/files/4983687/log.txt)

Let me know if you need more information.

**Comment by theimpulson** [comment]
Please test again on latest pre-release

**Comment by ochorocho** [comment]
@theimpulson tested on the latest release. Audio Issue still exists.

Here the logs when trying to play a youtube video:
[youtube.txt](https://github.com/HyperTeam/android_device_redmi_begonia/files/5016113/youtube.txt)

Let me know if you need more debugging information

Thank you :-)

**Comment by ochorocho** [comment]
Now working with lineage-17.1-20201227-UNOFFICIAL release.

Thank you! Keep up the good work. :-)
